### ISSUE TITLE
Uncaught ReferenceError: OpenSeadragon is not defined

### ISSUE THREAD

**Issue by mdushkoff** [pearcetm/GeoTIFFTileSource#14]
When creating a basic application using the npm package version of GeoTIFFTileSource `2.0.1` and OpenSeadragon `4.1.1`, the webpage fails to load OpenSeadragon, stating that it is undefined.

```
Uncaught ReferenceError: OpenSeadragon is not defined
```

I followed the instructions provided, using the example code:

```
import OpenSeadragon from 'openseadragon';
import { enableGeoTIFFTileSource } from "geotiff-tilesource";

enableGeoTIFFTileSource(OpenSeadragon);
```

Disabling the `geotiff-tilesource` import results in a working OpenSeadragon viewer so there is something wrong with the wrapper code causing the module to become invalid.

Please let me know if there is something that I'm doing incorrectly, or if there is indeed something wrong with the package itself/versions of the packages.

**Comment by pearcetm** [comment]
Hmm, will have to look into this. Any further insights you've been able to glean as to what the problem might be @mdushkoff ? @abiswas97 any thoughts?

**Comment by pearcetm** [comment]
@abiswas97 On the line below, `OpenSeadragon` is accessed but it isn't imported in this file. I believe this is the root of the problem. We need to figure out how to make this work right with both the npm package and the plain script.

https://github.com/pearcetm/GeoTIFFTileSource/blob/ff409312827b1d81ebdc70ee1da0211e90ba3b8f/src/GeoTIFFTileSource.js#L27

**Comment by mdushkoff** [comment]
With the merge above this should now be resolved.  I'm doing some more extensive testing now, so I'll re-open if I run into something strange.
