### ISSUE TITLE
OpenSeadragon v5 support

### ISSUE THREAD

**Issue by tjbanks** [pearcetm/GeoTIFFTileSource#22]
I'm running into issues updating OpenSeadragon to version 5. Any opposition to adding to the allowed dependencies?

**Comment by pearcetm** [comment]
No opposition at all!

**Comment by tjbanks** [comment]
Wonderful! I've created an MR here for your approval -- https://github.com/pearcetm/GeoTIFFTileSource/pull/23

**Comment by tjbanks** [comment]
This one is a little more clean -- https://github.com/pearcetm/GeoTIFFTileSource/pull/24/files

**Comment by tjbanks** [comment]
Thanks again!
